version: "3.8"

services:
  backend:
    container_name: rast_mobile_backend
    image: node:0.0.1
    ports:
      - "3001:3001"
    build:
      context: .
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - node_db:/var/lib/postgresql/data
volumes:
  node_db: {}
